--- 
author: ~
build_requires: 
  Test::Deep: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: Perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Data-SExpression
no_index: 
  directory: 
    - build
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0
version: 0.36
